### ISSUE TITLE
`cannot open display` running geany docker

### ISSUE THREAD

**Issue by rohoet** [app4mc-rover/rover-example-app#2]
Following the readme until its end,  `geany &` works

but 

`docker run -v $(pwd):/root/workspace/driving_control -w /root/workspace/driving_control -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix arm32v6/rover-app:0.0.1 geany`
gives 
```
hostname: you must be root to change the host name
Geany: cannot open display
```

Maybe some configuration is missing.

**Comment by daschubert** [comment]
Please validate that all clients can access the host's x-server
```
$ xhost +
```
see https://docs.oracle.com/cd/E36784_01/html/E36870/xhost-1.html

If the problem persists, we have to dig deeper into this.

**Comment by rohoet** [comment]
Done it (`geany &` works).
I had to ssh into the rover with `-X` flag though.

Problem still persists 😕

**Comment by daschubert** [comment]
Ok, I will try it on my machine. Earliest next week. I guess it's a typo somewhere in the readme.

**Comment by SiegelDaniel** [comment]
I get the exact same error using the following configuration:

![grafik](https://user-images.githubusercontent.com/14983741/60381734-caff3300-9a59-11e9-8d83-7e8eb13b5120.png)

Docker version 18.09.5, build e8ff056

I made sure to follow the ReadMe exactly as described.

**Comment by daschubert** [comment]
I just tested it and it works for me.
- fresh Ubuntu 16.04 (as mentioned in the readme)
- Docker 18.09.7

I will close this issue for the time being. If somebody wants to check whether the problems are related to Ubuntu 18.04 and/or improve something related to this issue, feel free to reopen.
